/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 sans_nom.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sans_nom.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Parent.geometry} material={materials.VitrailTriple_THRASHMETAL_Legendes} rotation={[Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.Plan1.geometry} material={materials.VitrailTriple_THRASHMETAL_Legendes} />
        <mesh geometry={nodes.Plan2.geometry} material={materials.VitrailTriple_THRASHMETAL_Legendes} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/sans_nom.glb')
